apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-express-service
  namespace: deployflow-test
  labels: &id001
    app.kubernetes.io/name: node-express-service
    app.kubernetes.io/managed-by: deployflow
    app.kubernetes.io/instance: 9f2e75db-987d-46e7-8174-48af165c4fd8
spec:
  replicas: 1
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: node-express-service
        image: ghcr.io/damibegud/deployflow-node-express-fixture:ad2fe9f4022c7d96a778c29dc849302eb783848b
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4587
          name: http
        envFrom:
        - configMapRef:
            name: node-express-service-config
        env: []
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
